version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    command: redis-server --requirepass redispassword
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data_container:/data

  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: nestjsdb
    volumes:
      - mongodb_data_container:/data/db

  nestjs:
    container_name: nestjs-backend
    build: .
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      BITCOIN_NODE_URL: "${BITCOIN_NODE_URL}"
      DATABASE_URL: "mongodb://mongoadmin:mongopassword@mongo:27017/nestjsdb?authSource=admin"
      DATABASE_USER: "mongoadmin"
      DATABASE_PASSWORD: "mongopassword"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_USERNAME: "redisuser"
      REDIS_PASSWORD: "redispassword"
      REDIS_DB_NAME: "nestjsredis"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - nestjs_data_container:/usr/src/app
    links:
      - mongo
      - redis

  nginx:
    image: "nginx:latest"
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      nestjs:
        condition: service_started
    links:
      - nestjs

volumes:
  nestjs_data_container:
  mongodb_data_container:
  redis_data_container:
