# Use the official Node.js LTS (Long Term Support) image as a base
FROM node:lts

# Invalidate the cache
ARG CACHEBUST=1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application into the working directory
COPY . .

# Build the application
RUN npm run build

# Expose ports
EXPOSE 3000 9229

# Command to run the application
CMD ["npm", "--inspect=0.0.0.0:9229", "start"]
