version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data_container:/data

  mongo:
    image: "mongo:latest"
    container_name: mongo
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: nestjsdb
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile.dev
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      BITCOIN_NODE_URL: "${BITCOIN_NODE_URL}"
      DATABASE_URL: "mongodb://mongoadmin:mongopassword@mongo:27017/nestjsdb?authSource=admin"
      DATABASE_USER: "mongoadmin"
      DATABASE_PASSWORD: "mongopassword"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      NFT_STORAGE_TOKEN: "${NFT_STORAGE_TOKEN}"
      ARWEAVE_KEY: "${ARWEAVE_KEY}"
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - nestjs_data_container:/usr/src/app
    
volumes:
  nestjs_data_container:
  mongodb_data_container:
  redis_data_container:
