version: '3.8'

services:
  nestjs:
    container_name: nestjs-backend
    build: .
    ports:
      - "3000:3000"
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      BITCOIN_NODE_URL: "${BITCOIN_NODE_URL}"
      DATABASE_URL: "mongodb://mongoadmin:mongopassword@mongo:27017/nestjsdb?authSource=admin"
      DATABASE_USER: "mongoadmin"
      DATABASE_PASSWORD: "mongopassword"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_USERNAME: "redisuser"
      REDIS_PASSWORD: "redispassword"
      REDIS_DB_NAME: "nestjsredis"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - nestjs_data_container:/usr/src/app

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass redispassword
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data/redis

  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: nestjsdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  nestjs_data_container:
  mongodb_data_container:
  redis_data_container:
